# Header
menu:
  主页: /
  所有文章: /archives
  关于我: /aboutMe
# categories: /categories/
# tags: /tags/
  # 随笔: /tags/随笔

# SubNav
subnav:
   github: "https://github.com/houwhu/blog"
   zhihu: "https://www.zhihu.com/people/axe-fu-zi/activities"
   mail: "1065440895@qq.com"
   #qq: "#"
   weibo: "https://weibo.com/2908056451/profile?topnav=1&wvr=6&is_all=1"
  # rss: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
# excerpt_link: 阅读全文
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
# baidu_tongji: true
# google_analytics: true

favicon: /img/favicon.ico
#你的头像url
avatar: /img/fuzi.jpg

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: true
  app_id: CT6z4tRaQYBtc6PrsgQYVqq9-gzGzoHsz
  app_key: XvOMQnFR7uTY3vsnxAgxDBIK
  security: false

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  smackdown: https://github.com/smackgg/hexo-theme-smackdown
#是否开启“关于我”。
# 不开启——
aboutme: false
#开启——
# aboutme:

swift_search:
  enable: true

# comments system support
comments:
    # values: tabs | buttons
    style: tabs
    active: valine
    storage: true
    lazyload: false
    
# valine
valine:
    enable: true
    appid: CT6z4tRaQYBtc6PrsgQYVqq9-gzGzoHsz
    appkey: XvOMQnFR7uTY3vsnxAgxDBIK
    
